### ISSUE TITLE
Instructions `rand` should be able to be assigned to variables

### ISSUE THREAD

**Issue by ghost** [rjhunjhunwala/S.I.L.O.S#16]
It would be cool if we can do a thing like

```
a=stackPop
b=queuePop
c=rand
a+b
a+c
printInt a
```

**Comment by rjhunjhunwala** [comment]
I might e able to rig up some kind of feature to allow return values from functions will that be acceptable?

**Comment by rjhunjhunwala** [comment]
This feature, will be added in an upcoming update which will allow for actual evaluation of proper expressions, within these expressions certain (language defined) functions may be called.

**Comment by rjhunjhunwala** [comment]
@tuxcrafting rand now works on the other side of an equals sign.
