### ISSUE TITLE
Can't run latest version for TIO

### ISSUE THREAD

**Issue by AndrewSav** [rjhunjhunwala/S.I.L.O.S#20]
When I pull this for TryItOnline, I'm getting

" Error: Could not find or load main class Silos"

Something changed?

**Comment by rjhunjhunwala** [comment]
I believe I just fixed this, from what I understand it is a problem with my package declaration. Try it agian, and let me know how it turns out. Thanks for reporting, I'll leave this open till the issue can be resolved.

**Comment by AndrewSav** [comment]
Yes, it's working now.

**Comment by rjhunjhunwala** [comment]
@AndrewSav  I'm trying to test some code on TIO, is the new code live for TIO?

**Comment by AndrewSav** [comment]
@rjhunjhunwala not yet. Ask Dennis to pull on the channel
